package com.ctrip.infosec.flowtable4j.translate.esb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-04-02T12:38:13.154+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "ESB", 
                  wsdlLocation = "http://soa.dev.sh.ctriptravel.com/SOA.ESB/Ctrip.SOA.ESB.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class ESB extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ESB");
    public final static QName ESBSoap12 = new QName("http://tempuri.org/", "ESBSoap12");
    public final static QName ESBSoap = new QName("http://tempuri.org/", "ESBSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://soa.dev.sh.ctriptravel.com/SOA.ESB/Ctrip.SOA.ESB.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ESB.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://soa.dev.sh.ctriptravel.com/SOA.ESB/Ctrip.SOA.ESB.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ESB(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ESB(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ESB() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ESB(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ESB(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ESB(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ESBSoap
     */
    @WebEndpoint(name = "ESBSoap12")
    public ESBSoap getESBSoap12() {
        return super.getPort(ESBSoap12, ESBSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ESBSoap
     */
    @WebEndpoint(name = "ESBSoap12")
    public ESBSoap getESBSoap12(WebServiceFeature... features) {
        return super.getPort(ESBSoap12, ESBSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ESBSoap
     */
    @WebEndpoint(name = "ESBSoap")
    public ESBSoap getESBSoap() {
        return super.getPort(ESBSoap, ESBSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ESBSoap
     */
    @WebEndpoint(name = "ESBSoap")
    public ESBSoap getESBSoap(WebServiceFeature... features) {
        return super.getPort(ESBSoap, ESBSoap.class, features);
    }

}
