package com.ctrip.infosec.flowtable4j.translate.esb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-04-02T12:38:13.144+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ESBSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ESBSoap {

    @WebResult(name = "CommRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CommRequest", targetNamespace = "http://tempuri.org/", className = "com.ctrip.infosec.flowtable4j.translate.esb.CommRequest")
    @WebMethod(operationName = "CommRequest", action = "http://tempuri.org/CommRequest")
    @ResponseWrapper(localName = "CommRequestResponse", targetNamespace = "http://tempuri.org/", className = "com.ctrip.infosec.flowtable4j.translate.esb.CommRequestResponse")
    public java.lang.String commRequest(
        @WebParam(name = "requestXML", targetNamespace = "http://tempuri.org/")
        java.lang.String requestXML
    );

    @WebResult(name = "RequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Request", targetNamespace = "http://tempuri.org/", className = "com.ctrip.infosec.flowtable4j.translate.esb.Request")
    @WebMethod(operationName = "Request", action = "http://tempuri.org/Request")
    @ResponseWrapper(localName = "RequestResponse", targetNamespace = "http://tempuri.org/", className = "com.ctrip.infosec.flowtable4j.translate.esb.RequestResponse")
    public java.lang.String request(
        @WebParam(name = "requestXML", targetNamespace = "http://tempuri.org/")
        java.lang.String requestXML
    );
}
