
package com.ctrip.infosec.flowtable4j.translate.esb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-04-02T12:38:13.127+08:00
 * Generated source version: 3.0.2
 * 
 */
public final class ESBSoap_ESBSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "ESB");

    private ESBSoap_ESBSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ESB.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ESB ss = new ESB(wsdlURL, SERVICE_NAME);
        ESBSoap port = ss.getESBSoap();  
        
        {
        System.out.println("Invoking commRequest...");
        java.lang.String _commRequest_requestXML = "";
        java.lang.String _commRequest__return = port.commRequest(_commRequest_requestXML);
        System.out.println("commRequest.result=" + _commRequest__return);


        }
        {
        System.out.println("Invoking request...");
        java.lang.String _request_requestXML = "";
        java.lang.String _request__return = port.request(_request_requestXML);
        System.out.println("request.result=" + _request__return);


        }

        System.exit(0);
    }

}
